"""empty message

Revision ID: 08305989c396
Revises: 7d8b879408f9
Create Date: 2023-03-06 09:47:43.054096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08305989c396'
down_revision = '7d8b879408f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
