"""empty message

Revision ID: 77652d4b18f2
Revises: 24ffbd1312c8
Create Date: 2023-04-05 17:10:02.990078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77652d4b18f2'
down_revision = '24ffbd1312c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen_level', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('seen_level')

    # ### end Alembic commands ###
