"""empty message

Revision ID: dd9602b3edc1
Revises: 
Create Date: 2023-03-05 17:27:54.420000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9602b3edc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=12), nullable=False),
    sa.Column('fname', sa.String(length=12), nullable=False),
    sa.Column('lname', sa.String(length=12), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
